name: CI Hexo Blog Deploy LTS

on:
  push:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Deploy-Pages:
    name: Deploy Hexo Public To Pages
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - name: Checkout Repository master branch
        uses: actions/checkout@master
      - name: Setup Node.js 10.x
        uses: actions/setup-node@master
        with:
          node-version: "12.x"
      - name: Setup Hexo Dependencies
        env:
          YUQUE_TOKEN: ${{ secrets.YUQUE_TOKEN }}
        run: |
          npm install hexo-cli -g
          npm install yuque-hexo -g
          npm install
          npm run start
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          external_repository: jlovec1024/jlovec1024.github.io
          publish_branch: master
          publish_dir: ./public
          commit_message: ${{ github.event.head_commit.message }}


